name: Run tests on pull requests
on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - main
      - develop
      - "**"
jobs:
  test-ubuntu-noble:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Print env
        run: env | sort
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5 
        with:
          gradle-version: '8.13'
      - name: Test Library
        run: |
          chmod +x gradlew
          ./gradlew build test
        working-directory: j2735-2024-ffm-lib
  test-ubuntu-jammy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Print env
        run: env | sort
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.13'
      - name: Test Library
        run: |
          chmod +x gradlew
          ./gradlew build test
        working-directory: j2735-2024-ffm-lib



